### ISSUE TITLE
고생하셨습니다.

### ISSUE THREAD

**Issue by ryudg** [baboda212/node-ejs-gilmaro#4]
회원가입과 로그인 구현이 좋은 것 같습니다. 
찜목록도 로컬 스토리지에 추가 되는 아이디어도 좋습니다.
```html
<section class="main-visual"></section>
```
default 이미지가 없어서 처음 5초 동안 보여질 이미지가 없는 부분과

```css
.bookMarkList {
  top : 0;
}
```
추가하면 더 보기 좋을 것 같습니다.
